name: Deploy project

on:
  push:
    branches: [main]
    paths:
      - 'lambda/**'
      - 'gluejob/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ingest lambda
        run: |
          cd lambda/writestream
          mkdir -p package
          cp writestreams.py package/
          cd package
          zip -r ../writestream.zip .
          aws lambda update-function-code \
            --function-name writestreams \
            --zip-file fileb://../writestream.zip


      - name: Deploy Glue Job Script
        env:  
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GLUE_JOB_NAME: dailykpi                     
          GLUE_SERVICE_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/glue4dynamoread  
        run: |
          cd gluejob

          # Upload the Python script directly (no zip)
          aws s3 cp dailykpi.py s3://${{ secrets.S3_GLUE_SCRIPT_BUCKET }}/dailykpi.py

          # Check if Glue job exists
          if aws glue get-job --job-name $GLUE_JOB_NAME --region $AWS_REGION > /dev/null 2>&1; then
            echo "Glue job $GLUE_JOB_NAME exists. Updating job..."
            aws glue update-job --job-name $GLUE_JOB_NAME --job-update '{
              "Role": "'"$GLUE_SERVICE_ROLE"'",
              "Command": {
                "Name": "glueetl",
                "ScriptLocation": "s3://'"${{ secrets.S3_GLUE_SCRIPT_BUCKET }}"'/dailykpi.py",
                "PythonVersion": "3"
              },
              "DefaultArguments": {
                "--job-language": "python",
                "--DYNAMODB_TABLE": "bolt",
                "--S3_OUTPUT_PATH": "s3://'${{ secrets.S3_GLUE_SCRIPT_BUCKET }}'/kpi_output/"
              }
            }' --region $AWS_REGION
          else
            echo "Glue job $GLUE_JOB_NAME does not exist. Creating job..."
            aws glue create-job --name "$GLUE_JOB_NAME" --role "$GLUE_SERVICE_ROLE" \
              --command '{"Name":"glueetl","ScriptLocation":"s3://'${{ secrets.S3_GLUE_SCRIPT_BUCKET }}'/dailykpi.py","PythonVersion":"3"}' \
              --glue-version "5.0" \
              --max-capacity 2 \
              --timeout 10 \
              --default-arguments '{"--job-language":"python","--DYNAMODB_TABLE":"bolt","--S3_OUTPUT_PATH":"s3://'${{ secrets.S3_GLUE_SCRIPT_BUCKET }}'/kpi_output/"}' \
              --region "$AWS_REGION"
          fi
