name: Deploy project

on:
  push:
    branches: [main]
    paths:
      - 'lambda/**'
      - '.github/workflows/deploy.yml'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check Changed Paths
        id: changes
        run: |
          echo "## Detecting changes..."
          git fetch origin main
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            # First commit or new branch: compare against empty tree
            CHANGED=$(git diff --name-only ${{ github.sha }})
          else
            CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi
          echo "CHANGED FILES:"
          echo "$CHANGED"
          echo "$CHANGED" | grep -q "^lambda/write_streams/" && echo "ingest_lambda_changed=true" >> $GITHUB_OUTPUT


      - name: Deploy ingest_lambda (if changed)
        if: steps.changes.outputs.ingest_lambda_changed == 'true'
        run: |
          cd lambda/write_streams
          cp handler.py package/
          cd package && zip -r ../write_streams.zip .
          aws lambda update-function-code \
            --function-name write_streams \
            --zip-file fileb://../write_streams.zip

 
