name: Deploy project

on:
  push:
    branches: [main]
    paths:
      - 'lambda/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ingest_lambda
        run: |
          cd lambda/write_streams
          cp handler.py package/
          cd package && zip -r ../write_streams.zip .
          aws lambda update-function-code \
            --function-name write_streams \
            --zip-file fileb://../write_streams.zip
